import {StyleSheet} from 'react-native';
import {fs, wp} from '../../config';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: wp(120),
  },
  imgbox: {
    marginTop: 5,
    height: wp(35),
    width: wp(35),
    borderRadius: wp(35),
    overflow: 'hidden',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userIcon: {
    width: '100%',
    height: undefined,
    aspectRatio: 1,
  },
  followCircle: {
    width: wp(15),
    height: wp(15),
    borderRadius: 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -2,
    left: 14,
    backgroundColor: 'purple',
  },
  boxWithText: {
    marginTop: 10,
    width: 46,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  displaybox: {
    paddingHorizontal: '5%',
    paddingVertical: 10,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  views: {
    fontSize: fs(12),
    lineHeight: fs(13),
    marginBottom: 2,
    width: '100%',
    color: 'white',
  },
  username: {
    fontSize: fs(15),
    lineHeight: fs(17),
    fontWeight: 'bold',
    width: '100%',
    textAlignVertical: 'center',
    marginBottom: 2,
    color: 'white',
  },
  caption: {
    fontSize: fs(14),
    lineHeight: fs(15),
    width: '100%',
    flexWrap: 'wrap',
    textAlignVertical: 'center',
    color: 'white',
  },
  text: {
    fontSize: fs(14),
    lineHeight: fs(15),
    color: 'white',
  },
  boldText: {
    fontSize: fs(14),
    lineHeight: fs(15),
    color: 'white',
    fontWeight: 'bold',
  },
  btnText: {
    fontWeight: 'bold',
    fontSize: fs(14),
    lineHeight: fs(15),
    textAlignVertical: 'center',
    color: 'white',
    marginTop: 5,
  },
  border: {
    borderColor: 'white',
    borderWidth: 1,
  },
  noBorder: {
    borderWidth: 0,
  },
  verifiedIcon: {
    width: wp(14),
    height: wp(14),
    borderRadius: wp(14),
    backgroundColor: 'purple',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
