import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    bottom: 120,
  },
  imgbox: {
    marginTop: 5,
    height: 35,
    width: 35,
    borderRadius: 35,
    overflow: 'hidden',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userIcon: {
    width: '100%',
    height: undefined,
    aspectRatio: 1,
  },
  followCircle: {
    width: 15,
    height: 15,
    borderRadius: 2,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    bottom: -2,
    left: 14,
    backgroundColor: 'purple',
  },
  boxWithText: {
    marginTop: 10,
    width: 46,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  displaybox: {
    paddingHorizontal: '5%',
    paddingVertical: 10,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  views: {
    fontSize: 12,
    lineHeight: 13,
    marginBottom: 2,
    width: '100%',
    color: 'white',
  },
  username: {
    fontSize: 15,
    lineHeight: 17,
    fontWeight: 'bold',
    width: '100%',
    textAlignVertical: 'center',
    marginBottom: 2,
    color: 'white',
  },
  caption: {
    fontSize: 14,
    lineHeight: 15,
    width: '100%',
    flexWrap: 'wrap',
    textAlignVertical: 'center',
    color: 'white',
  },
  text: {
    fontSize: 14,
    lineHeight: 15,
    color: 'white',
  },
  boldText: {
    fontSize: 14,
    lineHeight: 15,
    color: 'white',
    fontWeight: 'bold',
  },
  btnText: {
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 15,
    textAlignVertical: 'center',
    color: 'white',
    marginTop: 5,
  },
  border: {
    borderColor: 'white',
    borderWidth: 1,
  },
  noBorder: {
    borderWidth: 0,
  },
  verifiedIcon: {
    width: 14,
    height: 14,
    borderRadius: 14,
    backgroundColor: 'purple',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
